- name: Install packages for added security
  yum:
    name: httpd-tools
  tags: install_apcache_tools

- name: Make data directory
  file:
    path: "{{ item }}"
    state: directory
    owner: docker
    group: docker
    mode: '0655'
  loop:
    - /data/images
    - /home/docker/docker-registry/
    - /home/docker/docker-registry/auth
    - /home/docker/docker-registry/data
  tags: make_data_dir

- name: Copy docker images to remote machine
  copy:
    src: "{{ item }}"
    dest: /data/images
    owner: docker
    group: docker
    mode: '0755'
  loop:
    - httpd_offline.tar
    - registry_offline.tar
  tags: copy_docker_images

- name: Load registry image
  shell: docker load --input /data/images/registry_offline.tar
  tags: load_registry_image

- name: Load apache image
  shell: docker load --input /data/images/httpd_offline.tar
  tags: load_apache_image
  
- name: Copy apache configuration template to remote machine
  tepmlate:
    src: httpd.conf.j2
    dest: /home/docker/docker-registry/auth/httpd.conf
    owner: docker
    group: docker
    mode: '0755'
  tags: copy_apache_template

- name: Copy docker-compose template to remote machine
  template:
    src: docker-compose.yml.j2
    dest: /home/docker/docker-registry/docker-compose.yml
    owner: docker
    group: docker
    mode: '0644'
  tags: copy_docker_compose_template
    
- name: Update the local host file
  lineinfile:
    path: /etc/hosts
    regexp: '^127\.0\.0\.1'
    line:  127.0.0.1   localhost localhost.localdomain localhost4 localhost4.localdomain4  {{ registry_fqdn }}    {{ registry_ip }}
    owner: root
    group: root
    mode: '0644' 
  tags: update_host_file

- name: Add selinux rule
  sefcontext:
    target: '/home/docker/docker-registry/data(/.*)?'
    setype: httpd_config_t
    state: present
  tags: update_selinux

- name: Apply rule
  command: restorecon -irv /home/docker/docker-registry/data/
  tags: apply_selinux_rules
    
