- name: Install packages for added security
  yum:
    name: httpd-tools
  tags: install_apcache_tools

- name: Create Directory for http
  file:
    path: /home/docker/docker-registry/auth
    state: directory
    owner: docker
    group: docker
    mode: '0655'
  file:
    path: /home/docker/docker-registry/auth
    state: directory
    owner: docker
    group: docker
    mode: '0655'

- name: Install Apache template
  template:
    src: httpd.conf.j2
    deest: /home/docker/docker-registry/auth
    
 - name: Copy certs and key to auth directory
   shell: cp /home/docker/docker-registry/domain.crt /home/docker/docker-registry/auth/domain.crt
   shell: cp /home/docker/docker-registry/domain.key /home/docker/docker-registry/auth/domain.key

- name: Make data directory
  file:
    path: "{{ item }}"
    state: directory
    owner: docker
    group: docker
    mode: '0655'
  loop:
    - /data/images
    - /home/docker/docker-registry/
  tags: make_data_dir

- name: Copy docker images to remote machine
  copy:
    src: "{{ item }}"
    dest: /data/images
    owner: docker
    group: docker
    mode: '0755'
  loop:
    - httpd_offline.tar
    - registry_offline.tar
  tags: copy_docker_images

- name: Load registry image
  shell: docker load --input /data/images/registry_offline.tar
  tags: load_registry_image

- name: Load apache image
  shell: docker load --input /data/images/httpd_offline.tar
  tags: load_apache_image
  
- name: Copy docker-setup script to machine
  copy:
    src: docker-setup.sh
    dest: /home/docker/docker-registry/docker-setup.sh
    owner: docker
    group: docker
    mode: '0755'
  tags: copy_setup_script

- name: Update the local host file
  lineinfile:
    path: /etc/hosts
    regexp: '^127\.0\.0\.1'
    line:  127.0.0.1   localhost localhost.localdomain localhost4 localhost4.localdomain4  myregistrydomain.com    {{ registry_ip }}
    owner: root
    group: root
    mode: '0644' 
  tags: update_host_file

- name: Add selinux rule
  sefcontext:
    target: '/home/docker/docker-registry/data(/.*)?'
    setype: httpd_config_t
    state: present
  tags: update_selinux

- name: Apply rule
  command: restorecon -irv /home/docker/docker-registry/data/
  tags: apply_selinux_rules
    
