- name: Deploy secure offline registry
  hosts: localhost
  gather_facts: false
  become: true
  vars:
    - ansible_sudo_pass: SUDO_PASSWORD    # The installer_main.sh seds this with the users' input
    - registry_ip: REGISTRY_IP
    - registry_domain_name: REGISTRY_HOSTNAME

  roles:
    - deploy_secure_registry
