- name: Install docker and docker-ce 
  hosts: localhost
  gather_facts: false
  become: true
  vars: 
    - ansible_sudo_pass: SUDO_PASSWORD    # The installer_main.sh seds this with the users' input
    - docker_packages:
        - containerd.io-1.2.6-3.3.el7.x86_64.rpm
        - container-selinux-2.99-1.el7_6.noarch.rpm
        - docker-ce-18.09.8-3.el7.x86_64.rpm
        - docker-ce-cli-18.09.8-3.el7.x86_64.rpm
  roles: 
    - install_docker
 
