#- name: Update the system
#  yum:
#    name: '*'
#    state: latest

- name: Create installers directory
  file:
    path: "{{ item }}"
    state: directory
    owner: root
    group: root
    mode: '0655'
  loop:
    - /admin
    - /admin/installers/
    - /admin/installers/docker

- name: Copy installers to remote machine
  copy:
    src: "{{ item }}"
    dest: /admin/installers/docker
    owner: root
    group: root
    mode: '0655'
  loop:
    - containerd.io-1.2.6-3.3.el7.x86_64.rpm
    - container-selinux-2.99-1.el7_6.noarch.rpm
    - docker-ce-18.09.8-3.el7.x86_64.rpm
    - docker-ce-cli-18.09.8-3.el7.x86_64.rpm
  copy:
    src: docker-compose
    dest: /usr/local/bin/
    owner: root
    group: root
    mode: '0655'
        

- name: Install docker-ce
  shell: yum -y --disablerepo=* localinstall /admin/installers/docker/*.rpm

- name: Start docker daemon
  service:
    name: docker
    state: started
    enabled: true

- name: Create docker user
  user: 
    name: docker
    group: docker
    shell: /bin/bash
    groups: docker
    append: yes

- name: Update user paths
  copy:
    src: docker-compose.sh
    dest: /etc/profile.d/
    owner: root
    group: root
    mode: '0644'
